name: FrontEnd 

on: 
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  Carregamento-maquina:
    runs-on: windows-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: run install
        run: |
          cd frontEnd
          npm install
          npm run build
          npm test
  Teste:
    runs-on: windows-latest
      - uses: actions/checkout@v4
      - name:run teste
  Build:
    runs-on: windows-latest
      - uses: actions/checkout@v4
      - name: run build 