name: CI

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Entrar no dir
      run: cd ./frontEnd
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Build
      run: npm run build



        