name: FrontEnd 

on: 
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  Carregamento-maquina:
    runs-on: windows-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: run install
        run: |
          cd frontEnd
          npm install
          
  Teste:
    runs-on: windows-latest
    needs: [Carregamento-maquina]
    steps: 
      - uses: actions/checkout@v4
      - name: run teste
        run:  npm test

  build:
    runs-on: windows-latest
    needs: [Carregamento-maquina,Teste]
    steps: 
      - uses: actions/checkout@v4
      - name: run teste
        run:  npm run build