name: Av3 Action

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    

jobs:
  Av3-Action:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: run teste build
        run: cd ./frontEnd